#!/bin/bash

js="$(dirname $0)/clash.js"
latest="$(find . -type f -printf '%T@ %p\n' | sort -n | tail -1 | cut -f2- -d' ')"

case "$1" in

  "" | "status")
    node "$js" status
    ;;

  "join" | "joi" | "jo" | "j")
    node "$js" join "$2"
    ;;

  "start" | "star" | "sta" | "st")
    node "$js" start
    ;;

  "leave" | "leav" | "lea" | "le" | "l")
    node "$js" leave
    ;;

  "rejoin" | "rejoi" | "rejo" | "rej" | "re" | "r")
    node "$js" rejoin
    ;;

  "cases" | "case" | "cas" | "ca" | "c")
    node "$js" cases
    ;;

  "submit" | "submi" | "subm" | "sub" | "su" | "s")
    node "$js" submit "$latest" || exit
    name="$(basename $latest)"
    handle="$(jq .handle -r ~/.cocli/current.json)"
    mkdir -p ~/.cocli/submissions
    mv "$latest" ~/.cocli/submissions/"$handle-$name"
    ;;

  "test" | "tes" | "te" | "t")
    node "$js" test "$latest"
    ;;

  "board" | "boar" | "boa" | "bo" | "b")
    node "$js" board
    ;;

  *)
    node "$js" "$1" "$2"
    ;;

esac
